### PR TITLE
Port to 1.20.6

### LINKED ISSUE #334: update 1.20.5
Please update to 1.20.5 !

### PR DESCRIPTION
**Pull request by lonefelidae16**
Hi, long time no see 👋

Soooo many breaking changes are here, and unfortunately Mojang started to support the same feature as the Panorama Screens mod. I’m sad.

If I check them one by one, I’d run out of time, so I’ll pick up only the features that I’ve checked. I’ll make a pull each time I find a bug.

close #334 

- [x] Bedrock-like loading screens
- [x] Sheared Sheep Colors
- [x] Third person eating animations
- [x] Position and "paper doll" overlay
- [x] Dynamic Inactive Hud Opacity
- [x] Saving status overlay on Singleplayer world
- [x] 3D fishing hook
- [x] Bedrock Cauldrons that hold dyed water and potions
- [x] Bedrock Sun Glare
- [x] Bedrock Crafting Recipes (Toggleable)
- [x] Bedrock-like chat
- [x] Idle hand animations
- [x] Held item descriptions (enchantments, books and potions)
- [x] Reach-around block placement
- [x] Dying and Fallen Trees
- [x] Disable flying momentum (Drift) in creative mode
- [x] Stop elytra flying by pressing space on air
- [x] Bedrock bonemeal functionality for flowers and sugar cane
- [x] Bedrock Fire Aspect feature
- [x] Animal Eating Particle
- [x] HotBar animation when use items
- [x] Bigger item when holding an item on Inventory screen
- [x] Slot highlight feature

...Is that about right?

----

**The ~crazy amount of~ Changes**

Dependency Updates:
- yarn mappings 1.20.6+build.1
- fabric loader 0.15.10
- fabric api 0.97.8+1.20.6
- Mod Menu 10.0.0-beta.1
- Cloth Config 14.0.126
- Gradle 8.7
- Java 21

NBT Tag has been replaced by Component:
- affects all block entities, inventories, codecs and enchantments

Particle Spawn System has been replaced by Payload System:
- see ~`client.payloads.*`~ moved to `common.payloads.*`

Part of ActionResult has been split into ItemActionResult.

Update mixins.

Update recipes.

Update WorldGen datapacks.

### CODE REVIEW

**Comment by juancarloscp52** [comment]
Hey! thank you so much. I was checking the last weekend the updates needed for bedrockify and decided to wait a little bit in order to read the item components changes, but it would have definitively taken me a lot more to port haha. Thank you.

I'll be testing the PR in depth and checking, i expect to merge it by the end of the weekend at worse.

**Comment by lonefelidae16** [comment]
Haha, I think this update is really massive and makes developers cry. What’s the deal with adding 866 lines?
I might commit when I notice codes that could be described more cleanly, or that I implemented without much thought.

I’ll also be installing on my dedicated server and doing some debugging play.

**Comment by tianazhu** [comment]
Will it keep the hotbar animation item usage animation. I don't see you mentioning this feature on here?

**Comment by lonefelidae16** [comment]
> Will it keep the hotbar animation item usage animation. I don't see you mentioning this feature on here?

Oh, sorry. I just quoted from the README, so the basic functionality there will be maintained like HotBar animations, dragging item makes bigger, slot highlights. I'll update my comment.

**Comment by lonefelidae16** [comment]
@juancarloscp52 Sorry for the mention, but I received a new pull https://github.com/lonefelidae16/BedrockIfy/pull/2 , that adds a simple CI for all branches when pushing to repo.

Are you interested in setting up a CI/CD?
I don’t need this, but it affects this pull, so I leave this comment.
If the merge goes through as is, I’ll handle it on our side.

**Comment by juancarloscp52** [comment]
> @juancarloscp52 Sorry for the mention, but I received a new pull [lonefelidae16#2](https://github.com/lonefelidae16/BedrockIfy/pull/2) , that adds a simple CI for all branches when pushing to repo.
> 
> Are you interested in setting up a CI/CD? I don’t need this, but it affects this pull, so I leave this comment. If the merge goes through as is, I’ll handle it on our side.

I was planning on having some Delivery pipeline to publish on curseforge and modrinth more easily for this next release (similar to the ones i have in spyglass-improvements or panorama-screens). For the CI, at the moment i dont see much point to having just a build pipeline with nothing else.

**Comment by juancarloscp52** [comment]
I've finished reviewing and testing all functionality! Great work! thank you so much 🙂

**Comment by kikawaa** [comment]
When will sun glare get fixed? because it's broken since like 1.20.2 and is one of my favorite features in this mod and there are no alternatives

**Comment by lonefelidae16** [comment]
> When will sun glare get fixed? because it's broken since like 1.20.2 and is one of my favorite features in this mod and there are no alternatives

Sun Glare feature works for me (and also maybe Juan does since this is merged). Please provide details of your instance such as modlist, Fabric or Quilt, and its API version.

Similar issue is here #324

**Comment by kikawaa** [comment]
> Sun Glare feature works for me (and also maybe Juan does since this is merged). Please provide details of your instance such as modlist, Fabric or Quilt, and its API version.
> 
> Similar issue is here #324

I tried disabling Iris mod and sun glare started working, I think that code in BedrockIfy which detects whenever custom iris shaders are enabled or disabled is broken since like 1.20.2, because on 1.20.1 sun glare works even if iris is installed and disables itself only if custom shaders are enabled but on 1.20.4 and 1.20.6 at least, sun glare disables itself whenever Iris mod is installed even if custom shaders are not enabled.

**Pull request merged**
