### PR TITLE
[feat] Bedrock Sheep Colors

### LINKED ISSUE #120: Suggestion: Bedrock's Sheep colors
In Bedrock, sheep have their whole face and underbody dyed when a player dyes them. Not only that, but when you shear a sheep on bedrock, it attains its color on the sheared part of the texture.  Java keeps the sheep's face and underbody white. This is because Bedrock uses both of the sheep textures when coloring it. The Sheep has two separate Textures making up its model named, "sheep_fur" and "sheep". "sheep_fur" is the wool you see on the sheep while "sheep" is the texture below that with its face, legs, and sheared body texture. I know from experience with recourse pack making that you could port a java sheep texture to bedrock and it will have a colored face meaning that It has to do with the way the color is coded onto the sheep. It's not a whole separate texture from java's allowing it to do that. 

**Java's Sheep:**
image

**Bedrock's Sheep (Shaven to show the Color when you shear a bedrock sheep.):** 
image

### PR DESCRIPTION
**Pull request by lonefelidae16**
Oooops I’m really sorry! I completely forgot about the code I wrote myself.

This branch was created as a feature for 1.19.3, but it also works on 1.19.4.

----

resolve #120 

This enables the color of sheep wool to be displayed after shearing. It also supports a Disco sheep named “jeb_”.

A new configurable boolean `sheepColors` is available, and I haven’t added it to SettingsGUI. Please check `BedrockifyClientSettings.java`.

Also supports user modification by Resource pack. Thank you @Fuzss for your advice!

* new file `client.features.sheepColors.SheepSkinResource`
  - create sheared sheep texture at runtime

* update `BedrockifyClientSettings`
  - new field: boolean `sheepColors`
  - register new resource: `SheepSkinResource`

* update `BedrockIfyMixinPlugin`
  - disable this feature when optifabric is present

* registered mixin
  - `mixin.client.features.sheepColors.SheepWoolFeatureRendererMixin`

### CODE REVIEW

**Comment by Fuzss** [comment]
In case you're interested, [this mod](https://www.curseforge.com/minecraft/mc-mods/biome-sniffer) uses a better approach to implementing this feature which is compatible with a lot of resource packs. The idea is to dynamically generate `sheep_sheared.png` at runtime from the vanilla sheared sheep texture. The pixels that need to be colorized can be filtered out dynamically since they use the grayscale color space, while other parts of the texture like skin don't.

**Comment by lonefelidae16** [comment]
I checked it, yes it is very interesting approach.

So, how can I make only the skin transparent from the vanilla texture? If I choose to extract the part with zero saturation, this time even the eye color will change.

**Comment by Fuzss** [comment]
Yeah, I found that issue as well. My approach would be to simply ignore the upper 1-2% of grayscale space. Also limiting this rule to the face region of the texture file would make sense and limit a possible error with resource packs significantly. Might be important to determine the face region using relative uv coordinates since textures might have a higher resolution than vanilla.

I also went through a few resource packs and this approach seems to work well in theory.

**Comment by lonefelidae16** [comment]
Hm... I see. It may take a while, but I’ll try it.

I agree with you that it would be more user-friendly to be able to change it easily from the resource pack, as you mentioned. Thank you for sharing this.

**Comment by lonefelidae16** [comment]
Confirmed with:

* Accurate Sheep Wool
https://www.planetminecraft.com/texture-pack/accurate-sheep-wool-java-edition/
* Doubled resolution of vanilla sheep texture (128 x 64 pixels)
* Broke resolution of vanilla sheep texture (59 x 32 pixels)

**Pull request merged**
