### PR TITLE
Add Arabic Localization

### PR DESCRIPTION
**Pull request by E404NNF**

### CODE REVIEW

**Review by ABDULLAH0897 — APPROVED** [review]
Well Done @E404NNF 
so far it looks good. 
**Note:** some terms can not be translated into Arabic.

**Comment by E404NNF** [comment]
I tried translating and localizing as much as I can, some stuff aren't really that good looking at it now, but who tf cares?

**Review by juancarloscp52 — CHANGES_REQUESTED** [review]
BedrockIfy was updated a day or two after this PR, changing a lot of the translation keys and adding more translatable elements. Please add these new translations to the PR in order to approve it. Thanks for your translation and time!

**Comment by E404NNF** [comment]
Aight! I'll do it later

**Comment by E404NNF** [comment]
nvm i give up already, 111 lines to do? i'll just... leave them as they are (for now) because they isn't even arabic translation on bedorck

**Comment by juancarloscp52** [comment]
Yeah, don't worry about the loading tips, I don't expect to be all translated. Thanks for your work, this translation will be released with the next update

**Pull request merged**
